export const TodoMutations = {
  SET_LOADING: "LOADING_MUTATIONS",
  LOAD_USER_DATA: "LOAD_USER_DATA_MUTATIONS",
  LOAD_TODOD_DATA: "LOAD_TODOD_DATA_MUTATIONS",
  ADD_TASK: "ADD_TASK_MUTATIONS",
  DELETE_TASK: "DELETE_TASK_MUTATIONS",
  EDIT_TASK: "EDIT_TASK_MUTATIONS",
  SET_DUE_DATA: "SET_DUE_DATA_MUTATIONS",
  REARRANGE: "REARRANGE_MUTATIONS",
  UPDATE_PROGRESS: "UPDATE_PROGRESS_MUTATIONS",
  SET_USER_ID: "SET_USER_ID_MUTATIONS",
  SET_LOCAL_STORAGE: "SET_LOCAL_STORAGE_MUTATIONS",
  REMOVE_ALL_TASKS: "REMOVE_ALL_TASKS_MUTATIONS",
};

export const TodoActions = {
  SET_LOADING: "LOADING_ACTIONS",
  LOAD_USER_DATA: "LOAD_USER_DATA_ACTIONS",
  LOAD_TODOD_DATA: "LOAD_TODOD_DATA_ACTIONS",
  ADD_TASK: "ADD_TASK_ACTIONS",
  DELETE_TASK: "DELETE_TASK_ACTIONS",
  EDIT_TASK: "EDIT_TASK_ACTIONS",
  SET_DUE_DATA: "SET_DUE_DATA_ACTIONS",
  REARRANGE: "REARRANGE_ACTIONS",
  UPDATE_PROGRESS: "UPDATE_PROGRESS_ACTIONS",
  SET_USER_ID: "SET_USER_ID_ACTIONS",
  SET_LOCAL_STORAGE: "SET_LOCAL_STORAGE_ACTIONS",
  REMOVE_ALL_TASKS: "REMOVE_ALL_TASKS_ACTIONS",
};

export const UserMutations = {
  SET_LOADING: "SET_LOADING_MUTATIONS",
  SET_USER_INFO: "SET_USER_INFO_MUTATIONS",
  SET_IS_LOGGED_IN: "SET_IS_LOGGED_IN_MUTATIONS",
};

export const UserActions = {
  SET_LOADING: "SET_LOADING_ACTIONS",
  SET_USER_INFO: "SET_USER_INFO_ACTIONS",
  SET_IS_LOGGED_IN: "SET_IS_LOGGED_ACTIONS",
};
